###
GET http://localhost:3003/shopper/all

###
GET http://localhost:3003/shopper/product/16


###
POST http://localhost:3003/shopper/insert-pucharse
Content-Type: application/json

{
    "nameProduct": "AZEITE  PORTUGUÊS EXTRA VIRGEM GALLO 500ML",
    "productId": "16",
    "price": 20.49,
    "amount": 1
}

###
GET http://localhost:3003/shopper/pucharse-all


###
PUT http://localhost:3003/shopper/edit-amout/210215c9-1f91-44c3-be1a-251081bb2103
Content-Type: application/json

{
    "productId": "16",
    "amount": 2
}

###
DELETE http://localhost:3003/shopper/pucharse/210215c9-1f91-44c3-be1a-251081bb2103
###
DELETE http://localhost:3003/shopper/delete/pucharse